# Generated by Django 4.2 on 2025-06-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_entrenador_pokemon_entrenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='picture',
            field=models.ImageField(null=True, upload_to='entrenador_images'),
        ),
    ]
